doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            chronos_date: Warhuhn\Doctrine\DBAL\Types\ChronosDateType
            chronos_datetime: Warhuhn\Doctrine\DBAL\Types\ChronosDateTimeType
            chronos_datetimetz: Warhuhn\Doctrine\DBAL\Types\ChronosDateTimeTzType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
